---
# tasks file for sbaerlocher.traefik

- name: create traefik network
  become: true
  docker_network:
    name: '{{ traefik_network }}'
    ipam_config:
      - subnet: '{{ traefik_network_ipam.subnet }}'
        gateway: '{{ traefik_network_ipam.gateway }}'
        iprange: '{{ traefik_network_ipam.iprange }}'
  tags:
    - configuration

- name: create traefik directory
  become: true
  file:
    path: '{{ item }}'
    state: directory
    owner: root
    group: docker
    mode: 0550
  loop:
    - "{{ traefik_dir }}"
  loop_control:
    label: "{{ item }}"
  tags:
    - configuration

- name: configuration traefik
  become: true
  template:
    src: "{{ traefik_configuration_template }}"
    dest: "{{ traefik_dir }}/traefik.toml"
    owner: root
    group: docker
    mode: 0550
  notify:
    - restart proxy_1
  tags:
    - configuration

- name: start traefik
  become: true
  docker_container:
    name: proxy_1
    image: traefik
    restart_policy: unless-stopped
    published_ports:
      - '80:80'
      - '443:443'
    #   env:
    #     CF_API_EMAIL: "{{ traefik_dnschallenge_env.CF_API_EMAIL }}"
    #     CF_API_KEY: "{{ traefik_dnschallenge_env.CF_API_KEY }}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "{{ traefik_dir }}/traefik.toml:/etc/traefik/traefik.toml"
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik-data:/etc/traefik
    capabilities:
      - net_bind_service
    networks:
      - name: '{{ traefik_network }}'
    networks_cli_compatible: false
  tags:
    - configuration
